service: sls-deployment-test
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: MyBucket

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  world:
    handler: handler.world
    events:
      - httpApi:
          path: /world
          method: get

